import type { Job, Company, HiringPost, Keyword, TrackerRow } from './types';

const LOGO_COLORS = ['#2f7d5b','#3a6ea5','#a8682f','#7a5aa8','#b0563f','#3f8a8a','#9a7a2f','#6a6f7a'];

export function logoColor(name: string): string {
  let h = 0;
  for (let i = 0; i < name.length; i++) h = (h * 31 + name.charCodeAt(i)) % LOGO_COLORS.length;
  return LOGO_COLORS[h];
}

export function initials(name: string): string {
  const parts = name.replace(/[^A-Za-z0-9 ]/g, '').split(' ').filter(Boolean);
  if (parts.length === 1) return parts[0].slice(0, 2).toUpperCase();
  return (parts[0][0] + parts[1][0]).toUpperCase();
}

export function nameInitials(name: string): string {
  const p = name.trim().split(' ').filter(Boolean);
  return p.length > 1 ? p[0][0] + p[p.length - 1][0] : (p[0] || '?').slice(0, 2);
}

export function fmtMoney(n: number, cur: string, hourly?: boolean): string {
  const sym: Record<string, string> = { USD: '$', EUR: '€', INR: '₹', MYR: 'RM', GBP: '£' };
  const s = sym[cur] || '$';
  if (hourly) return `${s}${n}/hr`;
  if (cur === 'INR') return `${s}${(n / 100000).toFixed(0)}L`;
  if (n >= 1000) return `${s}${(n / 1000).toFixed(0)}k`;
  return `${s}${n}`;
}

export function payRange(j: Job): string {
  const sym: Record<string, string> = { USD: '$', EUR: '€', INR: '₹', MYR: 'RM' };
  const s = sym[j.currency] || '$';
  if (j.period === 'hr') return `${s}${j.min}–${s}${j.max}/hr`;
  if (j.currency === 'INR') return `${s}${(j.min / 100000).toFixed(0)}–${(j.max / 100000).toFixed(0)}L`;
  return `${s}${(j.min / 1000).toFixed(0)}k–${s}${(j.max / 1000).toFixed(0)}k`;
}

export const STATUS_META: Record<string, { label: string; color: string }> = {
  saved:        { label: 'Saved',        color: 'var(--st-saved)' },
  applied:      { label: 'Applied',      color: 'var(--st-applied)' },
  interviewing: { label: 'Interviewing', color: 'var(--st-interview)' },
  offer:        { label: 'Offer',        color: 'var(--st-offer)' },
  rejected:     { label: 'Rejected',     color: 'var(--st-rejected)' },
};

export const JOBS: Job[] = [
  { id: 'j1', role: 'Senior Frontend Engineer', company: 'Linear', region: 'worldwide', remote: 'Remote · Worldwide', currency: 'USD', min: 150000, max: 190000, period: 'yr', visa: false, type: 'Full-time', source: 'LinkedIn', posted: '2d', tags: ['React', 'TypeScript', 'Design Systems'], desc: 'Own the design-system layer of a fast, keyboard-first product.' },
  { id: 'j2', role: 'Staff Frontend Engineer', company: 'Vercel', region: 'worldwide', remote: 'Remote · Global', currency: 'USD', min: 180000, max: 240000, period: 'yr', visa: false, type: 'Full-time', source: 'Company site', posted: '4d', tags: ['Next.js', 'React', 'Edge'], desc: 'Shape the framework millions of developers ship on.' },
  { id: 'j3', role: 'Senior Frontend Engineer', company: 'Supabase', region: 'worldwide', remote: 'Remote · Worldwide', currency: 'USD', min: 140000, max: 185000, period: 'yr', visa: false, type: 'Full-time', source: 'LinkedIn', posted: '1d', tags: ['React', 'TypeScript', 'OSS'], desc: 'Build the dashboard for the open-source Firebase alternative.' },
  { id: 'j4', role: 'Frontend Engineer (React)', company: 'Zapier', region: 'worldwide', remote: 'Remote · Worldwide', currency: 'USD', min: 135000, max: 175000, period: 'yr', visa: false, type: 'Full-time', source: 'Wellfound', posted: '6d', tags: ['React', 'GraphQL'], desc: 'Automate work for millions on a fully-distributed team.' },
  { id: 'j5', role: 'Senior Frontend Developer', company: 'Razorpay', region: 'india', remote: 'Remote · India', currency: 'INR', min: 4500000, max: 6500000, period: 'yr', visa: false, type: 'Full-time', source: 'LinkedIn', posted: '3d', tags: ['React', 'TypeScript', 'Fintech'], desc: 'Build payment experiences used across India.' },
  { id: 'j6', role: 'SDE III — Frontend', company: 'Postman', region: 'india', remote: 'Remote · India', currency: 'USD', min: 70000, max: 95000, period: 'yr', visa: false, type: 'Full-time', source: 'Company site', posted: '5d', tags: ['React', 'API tooling'], desc: 'India-based, USD comp. Build the API platform.' },
  { id: 'j7', role: 'Senior Frontend Engineer', company: 'Hasura', region: 'india', remote: 'Remote · India', currency: 'USD', min: 60000, max: 85000, period: 'yr', visa: false, type: 'Full-time', source: 'LinkedIn', posted: '1w', tags: ['React', 'GraphQL'], desc: 'Remote-first, INR or USD payout options.' },
  { id: 'j8', role: 'Senior Frontend Engineer', company: 'GitLab', region: 'visa', remote: 'Remote · Sponsors visa', currency: 'USD', min: 130000, max: 170000, period: 'yr', visa: true, visaNote: 'US, UK, NL', type: 'Full-time', source: 'Company site', posted: '2d', tags: ['Vue', 'Ruby', 'OSS'], desc: 'All-remote, relocation & visa support for select regions.' },
  { id: 'j9', role: 'Frontend Engineer', company: 'Spotify', region: 'visa', remote: 'Hybrid · Stockholm', currency: 'EUR', min: 65000, max: 90000, period: 'yr', visa: true, visaNote: 'Sweden relocation', type: 'Full-time', source: 'LinkedIn', posted: '1w', tags: ['React', 'TypeScript'], desc: 'Relocation package + work-permit sponsorship.' },
  { id: 'j10', role: 'Senior Software Engineer, Web', company: 'Grab', region: 'visa', remote: 'On-site · Kuala Lumpur', currency: 'MYR', min: 180000, max: 260000, period: 'yr', visa: true, visaNote: 'Malaysia EP', type: 'Full-time', source: 'LinkedIn', posted: '4d', tags: ['React', 'Maps'], desc: 'Employment Pass sponsorship for SE-Asia super-app.' },
  { id: 'j11', role: 'Frontend Engineer', company: 'Booking.com', region: 'visa', remote: 'Hybrid · Amsterdam', currency: 'EUR', min: 70000, max: 95000, period: 'yr', visa: true, visaNote: 'NL highly-skilled migrant', type: 'Full-time', source: 'Company site', posted: '1w', tags: ['React', 'A/B'], desc: '30% ruling + relocation for the Netherlands.' },
  { id: 'j12', role: 'React Developer (Contract)', company: 'Toptal Client', region: 'freelance', remote: 'Remote · Worldwide', currency: 'USD', min: 60, max: 90, period: 'hr', visa: false, type: 'Contract', source: 'Toptal', posted: '2d', tags: ['React', 'Short-term'], desc: '3-month rolling contract, USD hourly.' },
  { id: 'j13', role: 'Senior Frontend (Freelance)', company: 'Braintrust', region: 'freelance', remote: 'Remote · Worldwide', currency: 'USD', min: 75, max: 110, period: 'hr', visa: false, type: 'Freelance', source: 'Braintrust', posted: '5d', tags: ['React', 'Web3'], desc: 'No middleman fees, paid in USD or crypto.' },
  { id: 'j14', role: 'Frontend Contractor', company: 'Gun.io Client', region: 'freelance', remote: 'Remote · US hours', currency: 'USD', min: 65, max: 95, period: 'hr', visa: false, type: 'Contract', source: 'Gun.io', posted: '1w', tags: ['React', 'TypeScript'], desc: '6-month contract, overlap US timezone.' },
];

export const COMPANIES: Company[] = [
  // ---- Detailed entries (with policy / visa / note) ----
  { name: 'GitLab',       region: 'Worldwide',    website: 'https://about.gitlab.com/',          linkedin: 'https://www.linkedin.com/company/gitlab-com/jobs/',     policy: 'All-remote',   visa: true,  currency: 'USD', roles: 12, note: 'Fully remote since day one, public handbook.' },
  { name: 'Zapier',       region: 'Worldwide',    website: 'https://zapier.com/',                linkedin: 'https://www.linkedin.com/company/zapier/jobs/',         policy: 'All-remote',   visa: false, currency: 'USD', roles: 5,  note: 'Distributed across 40+ countries.' },
  { name: 'Automattic',   region: 'Worldwide',    website: 'https://automattic.com/',            linkedin: 'https://www.linkedin.com/company/automattic/jobs/',     policy: 'All-remote',   visa: false, currency: 'USD', roles: 8,  note: 'Makers of WordPress.com, remote-first.' },
  { name: 'Deel',         region: 'Worldwide',    website: 'https://www.deel.com/',              linkedin: 'https://www.linkedin.com/company/deel-hq/jobs/',        policy: 'Remote-first', visa: true,  currency: 'USD', roles: 9,  note: 'Global payroll company, hires globally.' },
  { name: 'Remote',       region: 'Worldwide',    website: 'https://remote.com/',                linkedin: 'https://www.linkedin.com/company/remote-com/jobs/',     policy: 'All-remote',   visa: true,  currency: 'USD', roles: 6,  note: 'EOR platform, async culture.' },
  { name: 'Supabase',     region: 'Worldwide',    website: 'https://supabase.com/',              linkedin: 'https://www.linkedin.com/company/supabase/jobs/',       policy: 'All-remote',   visa: false, currency: 'USD', roles: 5,  note: 'Open-source, fully distributed.' },
  { name: 'Grab',         region: 'SE Asia',      website: 'https://grab.com/',                  linkedin: 'https://www.linkedin.com/company/grab/jobs/',           policy: 'Hybrid',       visa: true,  currency: 'MYR', roles: 6,  note: 'Visa sponsorship for Singapore & Malaysia.' },
  { name: 'Booking.com',  region: 'Netherlands',  website: 'https://www.booking.com/content/careers.en-gb.html', linkedin: 'https://www.linkedin.com/company/booking.com/jobs/', policy: 'Hybrid', visa: true, currency: 'EUR', roles: 10, note: 'Relocation + 30% tax ruling for NL.' },
  // ---- Full remote-company directory ----
  { name: '1Password',       region: 'North America, UK',        website: 'https://www.1password.com',              linkedin: 'https://www.linkedin.com/company/1password/jobs/' },
  { name: '42 Technologies', region: 'Worldwide',                website: 'https://www.42technologies.com/',         linkedin: 'https://www.linkedin.com/company/42-technologies-inc-/jobs/' },
  { name: 'abiturma',        region: 'Germany',                  website: 'https://www.abiturma.de/',                linkedin: 'https://www.linkedin.com/company/abiturma/jobs/' },
  { name: 'Ably',            region: 'Europe',                   website: 'https://www.ably.io/',                    linkedin: 'https://www.linkedin.com/company/ably-realtime/jobs/' },
  { name: 'Abstract API',    region: 'Worldwide',                website: 'https://www.abstractapi.com',             linkedin: 'https://www.linkedin.com/company/abstractapi/jobs/' },
  { name: 'acct',            region: 'Worldwide',                website: 'https://acct.global',                     linkedin: 'https://www.linkedin.com/company/acct-global/jobs/' },
  { name: 'Acivilate',       region: 'USA',                      website: 'https://acivilate.com/',                  linkedin: 'https://www.linkedin.com/company/acivilate/jobs/' },
  { name: 'Acquia',          region: 'Worldwide',                website: 'https://www.acquia.com/',                 linkedin: 'https://www.linkedin.com/company/acquia/jobs/' },
  { name: 'ActiveCampaign',  region: 'Dublin, Ireland; USA',     website: 'https://www.activecampaign.com/',         linkedin: 'https://www.linkedin.com/company/activecampaign/jobs/' },
  { name: 'Ad Hoc',          region: 'USA',                      website: 'https://www.adhocteam.us/',               linkedin: 'https://www.linkedin.com/company/ad-hoc-team/jobs/' },
  { name: 'Adaface',         region: 'Asia',                     website: 'https://www.adaface.com',                 linkedin: 'https://www.linkedin.com/company/adaface/jobs/' },
  { name: 'Adeva',           region: 'Asia, Africa, Europe, South America, USA', website: 'https://adevait.com/', linkedin: 'https://www.linkedin.com/company/adeva/jobs/' },
  { name: 'Adzuna',          region: 'Worldwide',                website: 'https://www.adzuna.co.uk/',               linkedin: 'https://www.linkedin.com/company/adzuna/jobs/' },
  { name: 'AE Studio',       region: 'USA, BR',                  website: 'https://ae.studio/',                      linkedin: 'https://www.linkedin.com/company/ae-studio/jobs/' },
  { name: 'AgFlow',          region: 'Europe',                   website: 'https://www.agflow.com',                  linkedin: 'https://www.linkedin.com/company/agflow/jobs/' },
  { name: 'Aha!',            region: 'Worldwide',                website: 'https://www.aha.io',                      linkedin: 'https://www.linkedin.com/company/aha-/jobs/' },
  { name: 'Airbank',         region: 'Europe, Americas, Africa, Western Asia', website: 'https://www.joinairbank.com/', linkedin: 'https://www.linkedin.com/company/joinairbank/jobs/' },
  { name: 'Airbyte',         region: 'Europe, North America, Latin America', website: 'https://airbyte.com/', linkedin: 'https://www.linkedin.com/company/airbyte/jobs/' },
  { name: 'Alan',            region: 'Europe',                   website: 'https://alan.com/',                       linkedin: 'https://www.linkedin.com/company/alan-insurance/jobs/' },
  { name: 'AlphaSights',     region: 'USA, UK',                  website: 'https://engineering.alphasights.com',     linkedin: 'https://www.linkedin.com/company/alphasights/jobs/' },
  { name: 'Amazon',          region: 'Worldwide',                website: 'https://www.amazon.jobs/en/locations/virtual-locations', linkedin: 'https://www.linkedin.com/company/amazon/jobs/' },
  { name: 'Andela',          region: 'Worldwide',                website: 'https://andela.com/',                     linkedin: 'https://www.linkedin.com/company/andela/jobs/' },
  { name: 'Animalz',         region: 'USA',                      website: 'https://www.animalz.co',                  linkedin: 'https://www.linkedin.com/company/animalz/jobs/' },
  { name: 'Appinio',         region: 'Europe',                   website: 'https://appinio.com/',                    linkedin: 'https://www.linkedin.com/company/appinio/jobs/' },
  { name: 'Applaudo',        region: 'Worldwide',                website: 'https://applaudostudios.com',             linkedin: 'https://www.linkedin.com/company/applaudo-studios/jobs/' },
  { name: 'Appwrite',        region: 'Worldwide',                website: 'https://appwrite.io',                     linkedin: 'https://www.linkedin.com/company/appwrite/jobs/' },
  { name: 'argyle',          region: 'Worldwide',                website: 'https://argyle.com/',                     linkedin: 'https://www.linkedin.com/company/argyle-systems/jobs/' },
  { name: 'Arkency',         region: 'Worldwide',                website: 'https://arkency.com/',                    linkedin: 'https://www.linkedin.com/company/arkency/jobs/' },
  { name: 'Art & Logic',     region: 'USA, Canada',              website: 'https://artandlogic.com',                 linkedin: 'https://www.linkedin.com/company/art-&-logic/jobs/' },
  { name: 'Articulate',      region: 'Worldwide',                website: 'https://www.articulate.com',              linkedin: 'https://www.linkedin.com/company/articulate/jobs/' },
  { name: 'Atlassian',       region: 'USA, Europe, Asia, Australia', website: 'https://www.atlassian.com/',         linkedin: 'https://www.linkedin.com/company/atlassian/jobs/' },
  { name: 'Audiense',        region: 'Worldwide',                website: 'https://www.audiense.com/',               linkedin: 'https://www.linkedin.com/company/audiense/jobs/' },
  { name: 'Aula Education',  region: 'Worldwide',                website: 'https://aula.education/',                 linkedin: 'https://www.linkedin.com/company/aula-education/jobs/' },
  { name: 'Auth0',           region: 'Worldwide',                website: 'https://auth0.com/',                      linkedin: 'https://www.linkedin.com/company/auth0/jobs/' },
  { name: 'Balsamiq',        region: 'Worldwide',                website: 'https://balsamiq.com/',                   linkedin: 'https://www.linkedin.com/company/balsamiq-studios/jobs/' },
  { name: 'Bandcamp',        region: 'Worldwide',                website: 'https://bandcamp.com/',                   linkedin: 'https://www.linkedin.com/company/bandcamp/jobs/' },
  { name: 'BandLab',         region: 'Worldwide',                website: 'https://bandlab.com/',                    linkedin: 'https://www.linkedin.com/company/bandlab-technologies/jobs/' },
  { name: 'Bandzoogle',      region: 'Worldwide',                website: 'https://bandzoogle.com/',                 linkedin: 'https://www.linkedin.com/company/bandzoogle/jobs/' },
  { name: 'Baremetrics',     region: 'Worldwide',                website: 'https://baremetrics.com/',                linkedin: 'https://www.linkedin.com/company/baremetrics/jobs/' },
  { name: 'Basecamp',        region: 'Worldwide',                website: 'https://basecamp.com/',                   linkedin: 'https://www.linkedin.com/company/basecamp/jobs/' },
  { name: 'BeBanjo',         region: 'Worldwide',                website: 'https://bebanjo.com/',                    linkedin: 'https://www.linkedin.com/company/bebanjo/jobs/' },
  { name: 'BeenVerified',    region: 'Worldwide',                website: 'https://www.beenverified.com/',           linkedin: 'https://www.linkedin.com/company/beenverified/jobs/' },
  { name: 'BeyondPricing',   region: 'USA, Europe',              website: 'https://beyondpricing.com',               linkedin: 'https://www.linkedin.com/company/beyondpricing/jobs/' },
  { name: 'Bitnami',         region: 'Worldwide',                website: 'https://bitnami.com/',                    linkedin: 'https://www.linkedin.com/company/bitnami/jobs/' },
  { name: 'Bitovi',          region: 'Worldwide',                website: 'https://bitovi.com/',                     linkedin: 'https://www.linkedin.com/company/bitovi/jobs/' },
  { name: 'Buffer',          region: 'Worldwide',                website: 'https://buffer.com/',                     linkedin: 'https://www.linkedin.com/company/bufferapp/jobs/' },
  { name: 'Bugfender',       region: 'Worldwide',                website: 'https://bugfender.com/',                  linkedin: 'https://www.linkedin.com/company/bugfender/jobs/' },
  { name: 'BuySellAds',      region: 'Worldwide',                website: 'https://www.buysellads.com/',             linkedin: 'https://www.linkedin.com/company/buysellads/jobs/' },
  { name: 'Calibre',         region: 'Worldwide',                website: 'https://calibreapp.com/',                 linkedin: 'https://www.linkedin.com/company/calibreapp/jobs/' },
  { name: 'Canonical',       region: 'Worldwide',                website: 'https://www.canonical.com/',              linkedin: 'https://www.linkedin.com/company/canonical/jobs/' },
  { name: 'Capchase',        region: 'Worldwide',                website: 'https://www.capchase.com/',               linkedin: 'https://www.linkedin.com/company/capchase/jobs/' },
  { name: 'CareMessage',     region: 'Worldwide',                website: 'https://caremessage.org/careers/',        linkedin: 'https://www.linkedin.com/company/caremessage/jobs/' },
  { name: 'Celsius',         region: 'Worldwide',                website: 'https://celsius.network/',                linkedin: 'https://www.linkedin.com/company/celsiusnetwork/jobs/' },
  { name: 'Chroma',          region: 'Worldwide',                website: 'https://hichroma.com/',                   linkedin: 'https://www.linkedin.com/company/chromaui/jobs/' },
  { name: 'CircleCI',        region: 'Worldwide',                website: 'https://circleci.com/',                   linkedin: 'https://www.linkedin.com/company/circleci/jobs/' },
  { name: 'CivicActions',    region: 'Worldwide',                website: 'https://civicactions.com/',               linkedin: 'https://www.linkedin.com/company/civicactions/jobs/' },
  { name: 'Civo',            region: 'Worldwide',                website: 'https://www.civo.com',                    linkedin: 'https://www.linkedin.com/company/civo/jobs/' },
  { name: 'Clevertech',      region: 'Worldwide',                website: 'https://clevertech.biz/',                 linkedin: 'https://www.linkedin.com/company/clevertech/jobs/' },
  { name: 'ClickUp',         region: 'Worldwide',                website: 'https://clickup.com/',                    linkedin: 'https://www.linkedin.com/company/clickup-app/jobs/' },
  { name: 'Close',           region: 'Worldwide',                website: 'https://close.com',                       linkedin: 'https://www.linkedin.com/company/close-crm/jobs/' },
  { name: 'Coalition Technologies', region: 'Worldwide',         website: 'https://coalitiontechnologies.com/',      linkedin: 'https://www.linkedin.com/company/coalition-technologies/jobs/' },
  { name: 'CodePen',         region: 'Worldwide',                website: 'https://codepen.io',                      linkedin: 'https://www.linkedin.com/company/codepen/jobs/' },
  { name: 'CodeSandbox',     region: 'Worldwide',                website: 'https://codesandbox.io',                  linkedin: 'https://www.linkedin.com/company/codesandbox/jobs/' },
  { name: 'Coinbase',        region: 'Worldwide',                website: 'https://www.coinbase.com',                linkedin: 'https://www.linkedin.com/company/coinbase/jobs/' },
  { name: 'Collabora',       region: 'Worldwide',                website: 'https://www.collabora.com/',              linkedin: 'https://www.linkedin.com/company/collabora/jobs/' },
  { name: 'ConsenSys',       region: 'Worldwide',                website: 'https://consensys.net/',                  linkedin: 'https://www.linkedin.com/company/consensys/jobs/' },
  { name: 'Coursera',        region: 'USA, Canada',              website: 'https://www.coursera.org/',               linkedin: 'https://www.linkedin.com/company/coursera/jobs/' },
  { name: 'Crossover',       region: 'Worldwide',                website: 'https://www.crossover.com',               linkedin: 'https://www.linkedin.com/company/crossover-for-work/jobs/' },
  { name: 'Crowdstrike',     region: 'Worldwide',                website: 'https://www.crowdstrike.com',             linkedin: 'https://www.linkedin.com/company/crowdstrike/jobs/' },
  { name: 'Customer.io',     region: 'Worldwide',                website: 'https://customer.io',                     linkedin: 'https://www.linkedin.com/company/customer.io/jobs/' },
  { name: 'DappRadar',       region: 'Worldwide',                website: 'https://dappradar.com/',                  linkedin: 'https://www.linkedin.com/company/dappradar/jobs/' },
  { name: 'DashboardHub',    region: 'Worldwide',                website: 'https://dashboardhub.io',                 linkedin: 'https://www.linkedin.com/company/dashboardhub/jobs/' },
  { name: 'Dashlane',        region: 'Worldwide',                website: 'https://dashlane.com',                    linkedin: 'https://www.linkedin.com/company/dashlane/jobs/' },
  { name: 'Datadog',         region: 'Worldwide',                website: 'https://www.datadoghq.com/',              linkedin: 'https://www.linkedin.com/company/datadog/jobs/' },
  { name: 'DataStax',        region: 'Worldwide',                website: 'https://www.datastax.com/',               linkedin: 'https://www.linkedin.com/company/datastax/jobs/' },
  { name: 'Delighted',       region: 'Worldwide',                website: 'https://delighted.com',                   linkedin: 'https://www.linkedin.com/company/delighted/jobs/' },
  { name: 'DigitalOcean',    region: 'Worldwide',                website: 'https://www.digitalocean.com/',           linkedin: 'https://www.linkedin.com/company/digitalocean/jobs/' },
  { name: 'Discord',         region: 'USA',                      website: 'https://discord.com/',                    linkedin: 'https://www.linkedin.com/company/discord/jobs/' },
  { name: 'Discourse',       region: 'Worldwide',                website: 'https://www.discourse.org/',              linkedin: 'https://www.linkedin.com/company/discourse/jobs/' },
  { name: 'DNSimple',        region: 'Worldwide',                website: 'https://dnsimple.com/',                   linkedin: 'https://www.linkedin.com/company/dnsimple/jobs/' },
  { name: 'Docker',          region: 'USA',                      website: 'https://www.docker.com',                  linkedin: 'https://www.linkedin.com/company/docker/jobs/' },
  { name: 'Doist',           region: 'Worldwide',                website: 'https://doist.com',                       linkedin: 'https://www.linkedin.com/company/doist/jobs/',          policy: 'All-remote', currency: 'USD', roles: 3, note: 'Async-first, makers of Todoist.' },
  { name: 'DroneDeploy',     region: 'Worldwide',                website: 'https://www.dronedeploy.com/',            linkedin: 'https://www.linkedin.com/company/dronedeploy/jobs/' },
  { name: 'Dropbox',         region: 'Worldwide',                website: 'https://www.dropbox.com/',                linkedin: 'https://www.linkedin.com/company/dropbox/jobs/' },
  { name: 'DuckDuckGo',      region: 'Worldwide',                website: 'https://duckduckgo.com/',                 linkedin: 'https://www.linkedin.com/company/ddg/jobs/' },
  { name: 'Elastic',         region: 'Worldwide',                website: 'https://www.elastic.co/',                 linkedin: 'https://www.linkedin.com/company/elastic-co/jobs/' },
  { name: 'Emsisoft',        region: 'Worldwide',                website: 'https://www.emsisoft.com/',               linkedin: 'https://www.linkedin.com/company/emsisoft/jobs/' },
  { name: 'Epam',            region: 'Worldwide',                website: 'https://epam.com/',                       linkedin: 'https://www.linkedin.com/company/epam-systems/jobs/' },
  { name: 'Epic Games',      region: 'Worldwide',                website: 'https://www.epicgames.com/',              linkedin: 'https://www.linkedin.com/company/epic-games/jobs/' },
  { name: 'Etsy',            region: 'Worldwide',                website: 'https://www.etsy.com/',                   linkedin: 'https://www.linkedin.com/company/etsy/jobs/' },
  { name: 'Evil Martians',   region: 'Worldwide',                website: 'https://evilmartians.com/',               linkedin: 'https://www.linkedin.com/company/evil-martians/jobs/' },
  { name: 'Evrone',          region: 'Worldwide',                website: 'https://evrone.com/',                     linkedin: 'https://www.linkedin.com/company/evrone/jobs/' },
  { name: 'Eyeo (Adblock Plus)', region: 'Worldwide',           website: 'https://eyeo.com/',                       linkedin: 'https://www.linkedin.com/company/eyeo/jobs/' },
  { name: 'FactorialHR',     region: 'Worldwide',                website: 'https://www.factorialhr.com',             linkedin: 'https://www.linkedin.com/company/factorial-hr/jobs/' },
  { name: 'Fastly',          region: 'Worldwide',                website: 'https://www.fastly.com/',                 linkedin: 'https://www.linkedin.com/company/fastly/jobs/' },
  { name: 'Fauna',           region: 'Worldwide',                website: 'https://www.fauna.com/',                  linkedin: 'https://www.linkedin.com/company/fauna-inc/jobs/' },
  { name: 'FFW Agency',      region: 'Worldwide',                website: 'https://ffwagency.com/',                  linkedin: 'https://www.linkedin.com/company/ffwagency/jobs/' },
  { name: 'Fly.io',          region: 'Worldwide',                website: 'https://fly.io',                          linkedin: 'https://www.linkedin.com/company/fly-io/jobs/' },
  { name: 'Focusnetworks',   region: 'Worldwide',                website: 'https://focusnetworks.com.br',            linkedin: 'https://www.linkedin.com/company/focusnetworks/jobs/' },
  { name: 'Formstack',       region: 'Worldwide',                website: 'https://www.formstack.com/',              linkedin: 'https://www.linkedin.com/company/formstack/jobs/' },
  { name: 'Freeagent',       region: 'Worldwide',                website: 'https://www.freeagent.com/',              linkedin: 'https://www.linkedin.com/company/freeagent/jobs/' },
  { name: 'Functionize',     region: 'Worldwide',                website: 'https://www.functionize.com/',            linkedin: 'https://www.linkedin.com/company/functionize/jobs/' },
  { name: 'General Assembly',region: 'Worldwide',                website: 'https://generalassemb.ly/',               linkedin: 'https://www.linkedin.com/company/general-assembly/jobs/' },
  { name: 'Ghost Foundation',region: 'Worldwide',                website: 'https://ghost.org/',                      linkedin: 'https://www.linkedin.com/company/ghost-foundation/jobs/' },
  { name: 'Glitch',          region: 'Worldwide',                website: 'https://www.glitch.com/',                 linkedin: 'https://www.linkedin.com/company/glitch-inc/jobs/' },
  { name: 'GoDaddy',         region: 'Worldwide',                website: 'https://www.godaddy.com/',                linkedin: 'https://www.linkedin.com/company/godaddy/jobs/' },
  { name: 'GoHiring',        region: 'Worldwide',                website: 'https://www.gohiring.com/',               linkedin: 'https://www.linkedin.com/company/gohiring/jobs/' },
  { name: 'Grafana Labs',    region: 'USA and EMEA/EST Timezones', website: 'https://grafana.com/',                  linkedin: 'https://www.linkedin.com/company/grafana-labs/jobs/' },
  { name: 'Graylog',         region: 'Worldwide',                website: 'https://www.graylog.org/',                linkedin: 'https://www.linkedin.com/company/graylog/jobs/' },
  { name: 'Groove',          region: 'Worldwide',                website: 'https://www.groovehq.com',                linkedin: 'https://www.linkedin.com/company/groove/jobs/' },
  { name: 'Gruntwork',       region: 'Worldwide',                website: 'https://www.gruntwork.io/',               linkedin: 'https://www.linkedin.com/company/gruntwork-io/jobs/' },
  { name: 'Hanno',           region: 'Worldwide',                website: 'https://hanno.co/',                       linkedin: 'https://www.linkedin.com/company/hanno/jobs/' },
  { name: 'Harvest',         region: 'Worldwide',                website: 'https://www.getharvest.com/',             linkedin: 'https://www.linkedin.com/company/harvest/jobs/' },
  { name: 'Help Scout',      region: 'Worldwide',                website: 'https://www.helpscout.net/',              linkedin: 'https://www.linkedin.com/company/help-scout/jobs/' },
  { name: 'Honeybadger',     region: 'Worldwide',                website: 'https://www.honeybadger.io/',             linkedin: 'https://www.linkedin.com/company/honeybadger-io/jobs/' },
  { name: 'Hotjar',          region: 'Worldwide',                website: 'https://careers.hotjar.com/',             linkedin: 'https://www.linkedin.com/company/hotjar/jobs/',         policy: 'All-remote', currency: 'EUR', roles: 4, note: 'Remote within ±3h of CET.' },
  { name: 'Human Made',      region: 'Worldwide',                website: 'https://hmn.md',                          linkedin: 'https://www.linkedin.com/company/human-made/jobs/' },
  { name: 'Hypothesis',      region: 'Worldwide',                website: 'https://hypothes.is',                     linkedin: 'https://www.linkedin.com/company/hypothesis/jobs/' },
  { name: 'IBM',             region: 'Worldwide',                website: 'https://www.ibm.com',                     linkedin: 'https://www.linkedin.com/company/ibm/jobs/' },
  { name: 'IDoneThis',       region: 'Worldwide',                website: 'https://idonethis.com/',                  linkedin: 'https://www.linkedin.com/company/idonethis/jobs/' },
  { name: 'Instamobile',     region: 'Worldwide',                website: 'https://instamobile.io',                  linkedin: 'https://www.linkedin.com/company/instamobile/jobs/' },
  { name: 'Intercom',        region: 'Worldwide',                website: 'https://www.intercom.io/',                linkedin: 'https://www.linkedin.com/company/intercom/jobs/' },
  { name: 'Intuit Inc.',     region: 'Worldwide',                website: 'https://www.intuit.com/',                 linkedin: 'https://www.linkedin.com/company/intuit/jobs/' },
  { name: 'Intuition Machines', region: 'Worldwide',            website: 'https://www.imachines.com/',              linkedin: 'https://www.linkedin.com/company/intuitionmachines/jobs/' },
  { name: 'InVision',        region: 'Worldwide',                website: 'https://www.invisionapp.com/',            linkedin: 'https://www.linkedin.com/company/invisionapp/jobs/' },
  { name: 'IOHK',            region: 'Worldwide',                website: 'https://iohk.io/',                        linkedin: 'https://www.linkedin.com/company/iohk/jobs/' },
  { name: 'IPInfo',          region: 'Worldwide',                website: 'https://ipinfo.io/',                      linkedin: 'https://www.linkedin.com/company/ipinfo/jobs/' },
  { name: 'IQVIA',           region: 'Worldwide',                website: 'https://jobs.iqvia.com/',                 linkedin: 'https://www.linkedin.com/company/iqvia/jobs/' },
  { name: 'iRonin',          region: 'Worldwide',                website: 'https://www.ironin.it/',                  linkedin: 'https://www.linkedin.com/company/ironin-it/jobs/' },
  { name: 'Iterative',       region: 'Worldwide',                website: 'https://www.iterative.ai/',               linkedin: 'https://www.linkedin.com/company/iterativeai/jobs/' },
  { name: 'iwantmyname',     region: 'Worldwide',                website: 'https://iwantmyname.com/',                linkedin: 'https://www.linkedin.com/company/iwantmyname/jobs/' },
  { name: 'Jaya Tech',       region: 'Worldwide',                website: 'https://jaya.tech/',                      linkedin: 'https://www.linkedin.com/company/jaya-tech/jobs/' },
  { name: 'Jitbit',          region: 'Worldwide',                website: 'https://www.jitbit.com/',                 linkedin: 'https://www.linkedin.com/company/jitbit/jobs/' },
  { name: 'Jitera',          region: 'Worldwide',                website: 'https://iruuza-inc.com/',                 linkedin: 'https://www.linkedin.com/company/jitera/jobs/' },
  { name: 'Kaggle',          region: 'Worldwide',                website: 'https://kaggle.com/',                     linkedin: 'https://www.linkedin.com/company/kaggle/jobs/' },
  { name: 'Kentik',          region: 'USA, Europe, APAC',        website: 'https://www.kentik.com/careers',          linkedin: 'https://www.linkedin.com/company/kentik/jobs/' },
  { name: 'Kinsta',          region: 'Worldwide',                website: 'https://kinsta.com',                      linkedin: 'https://www.linkedin.com/company/kinsta/jobs/' },
  { name: 'Kissmetrics',     region: 'Worldwide',                website: 'https://www.kissmetrics.com/',            linkedin: 'https://www.linkedin.com/company/kissmetrics/jobs/' },
  { name: 'Kodify',          region: 'Worldwide',                website: 'https://kodify.io',                       linkedin: 'https://www.linkedin.com/company/kodify/jobs/' },
  { name: 'Komoot',          region: 'Worldwide',                website: 'https://www.komoot.com',                  linkedin: 'https://www.linkedin.com/company/komoot/jobs/' },
  { name: 'Kraken',          region: 'Worldwide',                website: 'https://kraken.com',                      linkedin: 'https://www.linkedin.com/company/kraken-exchange/jobs/' },
  { name: 'Labelbox',        region: 'Worldwide',                website: 'https://labelbox.com/',                   linkedin: 'https://www.linkedin.com/company/labelbox/jobs/' },
  { name: 'LeadIQ',          region: 'Worldwide',                website: 'https://leadiq.com/',                     linkedin: 'https://www.linkedin.com/company/leadiq/jobs/' },
  { name: 'Linaro',          region: 'Worldwide',                website: 'https://www.linaro.org/',                 linkedin: 'https://www.linkedin.com/company/linaro/jobs/' },
  { name: 'Linux Foundation',region: 'Worldwide',                website: 'https://www.linuxfoundation.org/',        linkedin: 'https://www.linkedin.com/company/the-linux-foundation/jobs/' },
  { name: 'Litmus',          region: 'Worldwide',                website: 'https://litmus.com/',                     linkedin: 'https://www.linkedin.com/company/litmus/jobs/' },
  { name: 'LivePerson',      region: 'Worldwide',                website: 'https://www.liveperson.com/',             linkedin: 'https://www.linkedin.com/company/liveperson/jobs/' },
  { name: 'LogDNA',          region: 'Worldwide',                website: 'https://logdna.com',                      linkedin: 'https://www.linkedin.com/company/logdna/jobs/' },
  { name: 'Lullabot',        region: 'Worldwide',                website: 'https://www.lullabot.com/',               linkedin: 'https://www.linkedin.com/company/lullabot/jobs/' },
  { name: 'Luxoft',          region: 'Worldwide',                website: 'https://www.luxoft.com/',                 linkedin: 'https://www.linkedin.com/company/luxoft/jobs/' },
  { name: 'MailerLite',      region: 'Worldwide',                website: 'https://www.mailerlite.com',              linkedin: 'https://www.linkedin.com/company/mailerlite/jobs/' },
  { name: 'Mapbox',          region: 'Worldwide',                website: 'https://www.mapbox.com/',                 linkedin: 'https://www.linkedin.com/company/mapbox/jobs/' },
  { name: 'MarsBased',       region: 'Worldwide',                website: 'https://marsbased.com/',                  linkedin: 'https://www.linkedin.com/company/marsbased/jobs/' },
  { name: 'Memberful',       region: 'Worldwide',                website: 'https://memberful.com',                   linkedin: 'https://www.linkedin.com/company/memberful/jobs/' },
  { name: 'Memory',          region: 'Worldwide',                website: 'https://memory.ai/',                      linkedin: 'https://www.linkedin.com/company/memory-ai/jobs/' },
  { name: 'Merico',          region: 'Worldwide',                website: 'https://merico.dev/',                     linkedin: 'https://www.linkedin.com/company/merico/jobs/' },
  { name: 'MetaLab',         region: 'Worldwide',                website: 'https://metalab.co',                      linkedin: 'https://www.linkedin.com/company/metalab/jobs/' },
  { name: 'MetaMask',        region: 'Worldwide',                website: 'https://metamask.io',                     linkedin: 'https://www.linkedin.com/company/metamask/jobs/' },
  { name: 'MeteorOps',       region: 'Worldwide',                website: 'https://meteorops.com',                   linkedin: 'https://www.linkedin.com/company/meteorops/jobs/' },
  { name: 'Microsoft',       region: 'Worldwide',                website: 'https://www.microsoft.com/',              linkedin: 'https://www.linkedin.com/company/microsoft/jobs/' },
  { name: 'Mixmax',          region: 'Worldwide',                website: 'https://mixmax.com',                      linkedin: 'https://www.linkedin.com/company/mixmax/jobs/' },
  { name: 'MixRank',         region: 'Worldwide',                website: 'https://mixrank.com',                     linkedin: 'https://www.linkedin.com/company/mixrank/jobs/' },
  { name: 'Mobile Jazz',     region: 'Worldwide',                website: 'https://mobilejazz.com',                  linkedin: 'https://www.linkedin.com/company/mobilejazz/jobs/' },
  { name: 'Modern Tribe',    region: 'Worldwide',                website: 'https://tri.be/',                         linkedin: 'https://www.linkedin.com/company/modern-tribe/jobs/' },
  { name: 'Modsquad',        region: 'Worldwide',                website: 'https://modsquad.com/',                   linkedin: 'https://www.linkedin.com/company/modsquad/jobs/' },
  { name: 'MongoDB',         region: 'Worldwide',                website: 'https://mongodb.com',                     linkedin: 'https://www.linkedin.com/company/mongodb/jobs/' },
  { name: 'Mozilla',         region: 'North America',            website: 'https://www.mozilla.org/',                linkedin: 'https://www.linkedin.com/company/mozilla/jobs/' },
  { name: 'Muck Rack',       region: 'Worldwide',                website: 'https://muckrack.com',                    linkedin: 'https://www.linkedin.com/company/muck-rack/jobs/' },
  { name: 'Mux',             region: 'Worldwide',                website: 'https://mux.com',                         linkedin: 'https://www.linkedin.com/company/mux-inc/jobs/' },
  { name: 'Nagarro',         region: 'Worldwide',                website: 'https://www.nagarro.com/en',              linkedin: 'https://www.linkedin.com/company/nagarro/jobs/' },
  { name: 'NodeSource',      region: 'Worldwide',                website: 'https://nodesource.com/',                 linkedin: 'https://www.linkedin.com/company/nodesource/jobs/' },
  { name: 'Nvidia',          region: 'Worldwide',                website: 'https://www.nvidia.com/',                 linkedin: 'https://www.linkedin.com/company/nvidia/jobs/' },
  { name: "O'Reilly Media",  region: 'USA, UK, JPN, CHN',        website: 'https://www.oreilly.com/',                linkedin: "https://www.linkedin.com/company/o'reilly-media/jobs/" },
  { name: 'Octopus Deploy',  region: 'Worldwide',                website: 'https://octopus.com/',                    linkedin: 'https://www.linkedin.com/company/octopus-deploy/jobs/' },
  { name: 'Okta',            region: 'Worldwide',                website: 'https://www.okta.com',                    linkedin: 'https://www.linkedin.com/company/okta-inc/jobs/' },
  { name: 'OmbuLabs',        region: 'Worldwide',                website: 'https://www.ombulabs.com/',               linkedin: 'https://www.linkedin.com/company/ombulabs/jobs/' },
  { name: 'Onna',            region: 'USA, Europe',              website: 'https://onna.com/',                       linkedin: 'https://www.linkedin.com/company/onna/jobs/' },
  { name: 'Oracle',          region: 'Worldwide',                website: 'https://www.oracle.com/',                 linkedin: 'https://www.linkedin.com/company/oracle/jobs/' },
  { name: 'OutsourcingDev',  region: 'Worldwide',                website: 'https://www.outsourcingdev.com/',         linkedin: 'https://www.linkedin.com/company/outsourcingdev/jobs/' },
  { name: 'Pagepro',         region: 'UK, PL, Europe',           website: 'https://pagepro.co',                      linkedin: 'https://www.linkedin.com/company/pagepro/jobs/' },
  { name: 'Parabol',         region: 'Worldwide',                website: 'https://www.parabol.co/',                 linkedin: 'https://www.linkedin.com/company/parabol/jobs/' },
  { name: 'Parsely',         region: 'Worldwide',                website: 'https://www.parse.ly/',                   linkedin: 'https://www.linkedin.com/company/parse.ly/jobs/' },
  { name: 'Particular Software', region: 'Worldwide',            website: 'https://particular.net',                  linkedin: 'https://www.linkedin.com/company/particular-software/jobs/' },
  { name: 'Pathable',        region: 'Worldwide',                website: 'https://pathable.com/',                   linkedin: 'https://www.linkedin.com/company/pathable/jobs/' },
  { name: 'PayU',            region: 'Worldwide',                website: 'https://corporate.payu.com',              linkedin: 'https://www.linkedin.com/company/payu/jobs/' },
  { name: 'Percona',         region: 'Worldwide',                website: 'https://www.percona.com',                 linkedin: 'https://www.linkedin.com/company/percona/jobs/' },
  { name: 'Pex',             region: 'Worldwide',                website: 'https://pex.com',                         linkedin: 'https://www.linkedin.com/company/pex/jobs/' },
  { name: 'Plex',            region: 'Worldwide',                website: 'https://plex.tv',                         linkedin: 'https://www.linkedin.com/company/plex/jobs/' },
  { name: 'Polygon',         region: 'Worldwide',                website: 'https://polygon.technology/',             linkedin: 'https://www.linkedin.com/company/0xpolygon/jobs/' },
  { name: 'Precision Nutrition', region: 'Worldwide',            website: 'https://www.precisionnutrition.com/',     linkedin: 'https://www.linkedin.com/company/precision-nutrition/jobs/' },
  { name: 'Prezly',          region: 'Worldwide',                website: 'https://www.prezly.com/',                 linkedin: 'https://www.linkedin.com/company/prezly/jobs/' },
  { name: 'Primer',          region: 'Worldwide',                website: 'https://primer.io/careers',               linkedin: 'https://www.linkedin.com/company/primer-api/jobs/' },
  { name: 'Prisma',          region: 'Worldwide',                website: 'https://www.prisma.io/',                  linkedin: 'https://www.linkedin.com/company/prisma-io/jobs/' },
  { name: 'Progress Engine', region: 'Worldwide',                website: 'https://www.progressengine.com/en',       linkedin: 'https://www.linkedin.com/company/progress-engine/jobs/' },
  { name: 'Prominent Edge',  region: 'Worldwide',                website: 'https://prominentedge.com/careers',       linkedin: 'https://www.linkedin.com/company/prominent-edge/jobs/' },
  { name: 'Puppet',          region: 'Worldwide',                website: 'https://puppet.com/',                     linkedin: 'https://www.linkedin.com/company/puppet/jobs/' },
  { name: 'QuestDB',         region: 'Worldwide',                website: 'https://questdb.io',                      linkedin: 'https://www.linkedin.com/company/questdb/jobs/' },
  { name: 'Quora',           region: 'Worldwide',                website: 'https://www.quora.com',                   linkedin: 'https://www.linkedin.com/company/quora/jobs/' },
  { name: 'Ramp',            region: 'Worldwide',                website: 'https://www.ramp.com/',                   linkedin: 'https://www.linkedin.com/company/ramp-financial/jobs/' },
  { name: 'RebelMouse',      region: 'Worldwide',                website: 'https://www.rebelmouse.com/',             linkedin: 'https://www.linkedin.com/company/rebelmouse/jobs/' },
  { name: 'ReCharge',        region: 'Worldwide',                website: 'https://rechargepayments.com/',           linkedin: 'https://www.linkedin.com/company/recharge-payments/jobs/' },
  { name: 'Red Hat',         region: 'Worldwide',                website: 'https://www.redhat.com',                  linkedin: 'https://www.linkedin.com/company/red-hat/jobs/' },
  { name: 'RemoteBase',      region: 'Worldwide',                website: 'https://remotebase.com',                  linkedin: 'https://www.linkedin.com/company/remotebase/jobs/' },
  { name: 'RenoFi',          region: 'Worldwide',                website: 'https://renofi.com/',                     linkedin: 'https://www.linkedin.com/company/renofi/jobs/' },
  { name: 'Replit',          region: 'Worldwide',                website: 'https://replit.com',                      linkedin: 'https://www.linkedin.com/company/repl-it/jobs/' },
  { name: 'Revolut',         region: 'Worldwide',                website: 'https://www.revolut.com/',                linkedin: 'https://www.linkedin.com/company/revolut/jobs/' },
  { name: 'Rocket.Chat',     region: 'Worldwide',                website: 'https://rocket.chat',                     linkedin: 'https://www.linkedin.com/company/rocket-chat/jobs/' },
  { name: 'rtCamp',          region: 'Worldwide',                website: 'https://rtcamp.com',                      linkedin: 'https://www.linkedin.com/company/rtcamp/jobs/' },
  { name: 'Safeguard Global',region: 'Worldwide',                website: 'https://www.safeguardglobal.com/',        linkedin: 'https://www.linkedin.com/company/safeguard-global/jobs/' },
  { name: 'Salesforce',      region: 'Worldwide',                website: 'https://www.salesforce.com/',             linkedin: 'https://www.linkedin.com/company/salesforce/jobs/' },
  { name: 'Scrapinghub',     region: 'Worldwide',                website: 'https://scrapinghub.com/',                linkedin: 'https://www.linkedin.com/company/scrapinghub/jobs/' },
  { name: 'ScyllaDB',        region: 'Worldwide',                website: 'https://scylladb.com/',                   linkedin: 'https://www.linkedin.com/company/scylladb/jobs/' },
  { name: 'Seaplane',        region: 'Worldwide',                website: 'https://www.seaplane.io/',                linkedin: 'https://www.linkedin.com/company/seaplane-io/jobs/' },
  { name: 'Semaphore',       region: 'Europe',                   website: 'https://semaphoreci.com',                 linkedin: 'https://www.linkedin.com/company/semaphore-ci/jobs/' },
  { name: 'Sendwave',        region: 'Worldwide',                website: 'https://www.sendwave.com/',               linkedin: 'https://www.linkedin.com/company/sendwave/jobs/' },
  { name: 'SerpApi',         region: 'Worldwide',                website: 'https://serpapi.com/',                    linkedin: 'https://www.linkedin.com/company/serpapi/jobs/' },
  { name: 'ServMask',        region: 'Worldwide',                website: 'https://servmask.com',                    linkedin: 'https://www.linkedin.com/company/servmask/jobs/' },
  { name: 'Session',         region: 'Worldwide',                website: 'https://getsession.com',                  linkedin: 'https://www.linkedin.com/company/loki-foundation/jobs/' },
  { name: 'Shogun',          region: 'Worldwide',                website: 'https://getshogun.com',                   linkedin: 'https://www.linkedin.com/company/shogun-web/jobs/' },
  { name: 'Shopify',         region: 'Worldwide',                website: 'https://www.shopify.com',                 linkedin: 'https://www.linkedin.com/company/shopify/jobs/' },
  { name: 'SignEasy',        region: 'Worldwide',                website: 'https://signeasy.com/',                   linkedin: 'https://www.linkedin.com/company/signeasy/jobs/' },
  { name: 'Silverfin',       region: 'Worldwide',                website: 'https://www.silverfin.com/',              linkedin: 'https://www.linkedin.com/company/silverfin/jobs/' },
  { name: 'SimpleTexting',   region: 'Worldwide',                website: 'https://simpletexting.com/',              linkedin: 'https://www.linkedin.com/company/simpletexting/jobs/' },
  { name: 'Skillshare',      region: 'Worldwide',                website: 'https://www.skillshare.com/teach',        linkedin: 'https://www.linkedin.com/company/skillshare/jobs/' },
  { name: 'Soshace',         region: 'Worldwide',                website: 'https://www.soshace.com/',                linkedin: 'https://www.linkedin.com/company/soshace/jobs/' },
  { name: 'Spotify',         region: 'Worldwide',                website: 'https://www.spotify.com/',                linkedin: 'https://www.linkedin.com/company/spotify/jobs/' },
  { name: 'Spreaker',        region: 'USA, Europe',              website: 'https://spreaker.com/',                   linkedin: 'https://www.linkedin.com/company/spreaker/jobs/' },
  { name: 'Stack Exchange',  region: 'Worldwide',                website: 'https://stackexchange.com/',              linkedin: 'https://www.linkedin.com/company/stack-exchange/jobs/' },
  { name: 'Status',          region: 'Worldwide',                website: 'https://www.status.im/',                  linkedin: 'https://www.linkedin.com/company/status-im/jobs/' },
  { name: 'Sticker Mule',    region: 'Worldwide',                website: 'https://www.stickermule.com/',            linkedin: 'https://www.linkedin.com/company/sticker-mule/jobs/' },
  { name: 'Strapi',          region: 'Worldwide',                website: 'https://strapi.io/careers',               linkedin: 'https://www.linkedin.com/company/strapi/jobs/' },
  { name: 'StreamNative',    region: 'Worldwide',                website: 'https://streamnative.io/careers/',        linkedin: 'https://www.linkedin.com/company/streamnative/jobs/' },
  { name: 'Stripe',          region: 'Worldwide',                website: 'https://stripe.com/',                     linkedin: 'https://www.linkedin.com/company/stripe/jobs/' },
  { name: 'SUSE',            region: 'Worldwide',                website: 'https://www.suse.com/',                   linkedin: 'https://www.linkedin.com/company/suse/jobs/' },
  { name: 'Teamflow',        region: 'Worldwide',                website: 'https://www.teamflowhq.com/',             linkedin: 'https://www.linkedin.com/company/teamflowhq/jobs/' },
  { name: 'Teleport',        region: 'USA, Europe',              website: 'https://teleport.org/',                   linkedin: 'https://www.linkedin.com/company/teleport-hq/jobs/' },
  { name: 'Telerik',         region: 'Worldwide',                website: 'https://www.telerik.com/',                linkedin: 'https://www.linkedin.com/company/progress/jobs/' },
  { name: 'Telestax',        region: 'Worldwide',                website: 'https://telestax.com/',                   linkedin: 'https://www.linkedin.com/company/telestax/jobs/' },
  { name: 'Tenable',         region: 'Worldwide',                website: 'https://www.tenable.com/',                linkedin: 'https://www.linkedin.com/company/tenableinc/jobs/' },
  { name: 'TestGorilla',     region: 'Worldwide',                website: 'https://www.testgorilla.com/',            linkedin: 'https://www.linkedin.com/company/testgorilla/jobs/' },
  { name: 'TheoremOne',      region: 'UTC-10 to UTC+2',         website: 'https://theoremone.co/',                  linkedin: 'https://www.linkedin.com/company/theoremone/jobs/' },
  { name: 'toggl',           region: 'Worldwide',                website: 'https://toggl.com/',                      linkedin: 'https://www.linkedin.com/company/toggl/jobs/' },
  { name: 'Toptal',          region: 'Worldwide',                website: 'https://www.toptal.com/',                 linkedin: 'https://www.linkedin.com/company/toptal/jobs/' },
  { name: 'Tower',           region: 'Worldwide',                website: 'https://www.git-tower.com/',              linkedin: 'https://www.linkedin.com/company/git-tower/jobs/' },
  { name: 'Travis CI',       region: 'Worldwide',                website: 'https://travis-ci.org/',                  linkedin: 'https://www.linkedin.com/company/travis-ci/jobs/' },
  { name: 'Turing',          region: 'Worldwide',                website: 'https://www.turing.com/',                 linkedin: 'https://www.linkedin.com/company/turing-labs/jobs/',    policy: 'Remote-first', currency: 'USD', roles: 20, note: 'Matches devs to US companies, USD pay.' },
  { name: 'Twilio',          region: 'Worldwide',                website: 'https://www.twilio.com/',                 linkedin: 'https://www.linkedin.com/company/twilio-inc-/jobs/' },
  { name: 'Udacity',         region: 'Worldwide',                website: 'https://www.udacity.com/',                linkedin: 'https://www.linkedin.com/company/udacity/jobs/' },
  { name: 'Uhuru',           region: 'Worldwide',                website: 'https://uhurunetwork.com/',               linkedin: 'https://www.linkedin.com/company/uhuru-network/jobs/' },
  { name: 'Ushahidi',        region: 'Worldwide',                website: 'https://www.ushahidi.com',                linkedin: 'https://www.linkedin.com/company/ushahidi/jobs/' },
  { name: 'Varnish Software',region: 'Worldwide',                website: 'https://www.varnishsoftware.com/',        linkedin: 'https://www.linkedin.com/company/varnish-software/jobs/' },
  { name: 'Vercel',          region: 'Worldwide',                website: 'https://vercel.com/',                     linkedin: 'https://www.linkedin.com/company/vercel/jobs/',         policy: 'Remote-first', visa: true, currency: 'USD', roles: 7, note: 'Frontend cloud, strong design culture.' },
  { name: 'Veryfi',          region: 'Worldwide',                website: 'https://veryfi.com/about',                linkedin: 'https://www.linkedin.com/company/veryfi/jobs/' },
  { name: 'VMware',          region: 'Worldwide',                website: 'https://www.vmware.com/',                 linkedin: 'https://www.linkedin.com/company/vmware/jobs/' },
  { name: 'WebFX',           region: 'Worldwide',                website: 'https://www.webfx.com',                   linkedin: 'https://www.linkedin.com/company/webfx/jobs/' },
  { name: 'Whitespectre',    region: 'Worldwide',                website: 'https://whitespectre.com',                linkedin: 'https://www.linkedin.com/company/whitespectre/jobs/' },
  { name: 'Wikimedia Foundation', region: 'Worldwide',          website: 'https://wikimediafoundation.org',         linkedin: 'https://www.linkedin.com/company/wikimedia-foundation/jobs/' },
  { name: 'Wildbit',         region: 'Worldwide',                website: 'https://wildbit.com/',                    linkedin: 'https://www.linkedin.com/company/wildbit/jobs/' },
  { name: 'Wizeline',        region: 'Worldwide',                website: 'https://www.wizeline.com/',               linkedin: 'https://www.linkedin.com/company/wizeline/jobs/' },
  { name: 'Wolfram',         region: 'Worldwide',                website: 'https://www.wolfram.com',                 linkedin: 'https://www.linkedin.com/company/wolfram-research/jobs/' },
  { name: 'WP-Media',        region: 'Worldwide',                website: 'https://wp-media.me/',                    linkedin: 'https://www.linkedin.com/company/wp-media/jobs/' },
  { name: 'X-Team',          region: 'Worldwide',                website: 'https://x-team.com/',                     linkedin: 'https://www.linkedin.com/company/x-team/jobs/' },
  { name: 'Xapo',            region: 'Worldwide',                website: 'https://xapo.com/en/',                    linkedin: 'https://www.linkedin.com/company/xapo/jobs/' },
  { name: 'Yandex',          region: 'Worldwide',                website: 'https://yandex.com/',                     linkedin: 'https://www.linkedin.com/company/yandex/jobs/' },
  { name: 'YAZIO',           region: 'Europe',                   website: 'https://www.yazio.com/en/jobs',           linkedin: 'https://www.linkedin.com/company/yazio/jobs/' },
  { name: 'Yodo1',           region: 'Worldwide',                website: 'https://www.yodo1.com/en/',               linkedin: 'https://www.linkedin.com/company/yodo1/jobs/' },
  { name: 'Yonder',          region: 'Worldwide',                website: 'https://www.yonder.io',                   linkedin: 'https://www.linkedin.com/company/yonder-io/jobs/' },
  { name: 'ZenRows',         region: 'Worldwide',                website: 'https://www.zenrows.com/',                linkedin: 'https://www.linkedin.com/company/zenrows/jobs/' },
  { name: 'Zip.co',          region: 'USA, Canada',              website: 'https://zip.co/us/',                      linkedin: 'https://www.linkedin.com/company/zipmoney/jobs/' },
];

export const HIRING_POSTS: HiringPost[] = [
  { name: 'Priya Nair', title: 'Eng Manager @ Stripe', when: '5h', text: 'We are hiring 2 Senior Frontend Engineers (React/TS) — fully remote, USD comp. DMs open!', role: 'Senior Frontend Engineer', company: 'Stripe' },
  { name: 'Daniel Roth', title: 'CTO @ a YC startup', when: '1d', text: 'Looking for a remote Staff Frontend Engineer. We sponsor visas for relocation to the US.', role: 'Staff Frontend Engineer', company: 'YC Startup' },
  { name: 'Mei Ling Tan', title: 'Recruiter @ Grab', when: '2d', text: 'Hiring Senior Web Engineers in Kuala Lumpur — Employment Pass sponsored. Comment "interested".', role: 'Senior Web Engineer', company: 'Grab' },
  { name: 'Arjun Mehta', title: 'Founder @ Devtools co.', when: '3d', text: 'Remote-from-India Senior Frontend role, paid in USD. React + TypeScript. Async team.', role: 'Senior Frontend Engineer', company: 'Devtools co.' },
  { name: 'Sofia Almeida', title: 'Talent @ GitLab', when: '4d', text: 'Multiple frontend openings, all-remote worldwide. Relocation support for select countries.', role: 'Frontend Engineer', company: 'GitLab' },
];

export const KEYWORD_SETS: Keyword[] = [
  { id: 'k1', label: 'Core role titles', value: '("Senior Frontend" OR "Frontend Engineer" OR "React Developer" OR "UI Engineer")' },
  { id: 'k2', label: 'Remote signals', value: '(remote OR "work from home" OR distributed OR "fully remote") -hybrid -onsite' },
  { id: 'k3', label: 'Visa / relocation', value: '("visa sponsorship" OR relocation OR "work permit" OR "Employment Pass")' },
  { id: 'k4', label: 'USD / foreign pay', value: '(USD OR "$" OR "paid in dollars" OR "foreign currency")' },
  { id: 'k5', label: 'Stack', value: '(React AND TypeScript) (Next.js OR Remix OR Vite)' },
  { id: 'k6', label: 'Exclusions', value: '-intern -junior -"3 days in office" -contract' },
];

export const TRACKER_SEED: TrackerRow[] = [];

export const PROFILE_DEFAULT = {
  name: 'Aman Kapoor',
  title: 'Senior Frontend Engineer',
  yoe: '7',
  location: 'Bengaluru, India',
  email: 'aman@example.com',
  linkedin: 'linkedin.com/in/amankapoor',
  github: 'github.com/amankapoor',
  skills: 'React, TypeScript, Next.js, Design Systems, GraphQL',
  noticePeriod: '30 days',
  currency: 'USD',
  targetCTC: '180000',
  openToVisa: true,
  openToRelocation: true,
  bio: '',
};
